import '@radix-ui/themes/styles.css';
import Header from './components/header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;700&display=swap" />
      </head>
      <body className={inter.className}>
      <Header />
        <main className=' dark:bg-amber-950 transition-colors'>
          {children}
        </main>
      </body>
    </html>
  )
}
