import '@radix-ui/themes/styles.css';
import Header from './components/header'
import './globals.css'
import { Inter } from 'next/font/google'
import SideBarra from './components/sidebar.jsx';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={inter.className}>
        <main className='h-screen w-screen bg-yellow-50 dark:bg-gray-800 transition-colors'>
          <Header />
<SideBarra />
          {children}
        </main>
      </body>
    </html>
  )
}
